#!/usr/bin/python3
import os
import gi
import sys
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

from includes.window import SingleTerminalWindow
from includes.util import ROOT_DIR

title = sys.argv[1] if len(sys.argv) >= 2 else "Default"
directory = sys.argv[2] if len(sys.argv) >= 3 else "Default"
commands = sys.argv[3:]  if len(sys.argv) >= 4 else []
popup = SingleTerminalWindow(title, directory, commands)  
Gtk.main()
